# Generated by Django 4.2.3 on 2023-08-23 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_session_date_alter_session_expiration_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.AlterField(
            model_name='session',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 20, 13, 3, 841855, tzinfo=datetime.timezone.utc)),
        ),
    ]
